import { Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/common/Navbar";
import Footer from "@/components/common/Footer";

const inter = Roboto({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata = {
  title: "Art Station",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Navbar />
        {children}
        <Footer />
        </body>
    </html>
  );
}
